# Generated by Django 4.1.7 on 2023-02-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=18)),
                ('amount', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=30)),
                ('paid_with', models.CharField(choices=[('rev', 'Revolut'), ('ing', 'ING')], max_length=7)),
            ],
        ),
    ]
